#!/bin/sh

printf "\n"
printf " * Documentation:  https://confluence.minervanetworks.com/Vagrant \n"
printf " * Management:     https://jira.minervanetworks.com [RHEL-LINK]   \n"
printf " * Support:        https://ubuntu.com/advantage\n"
printf "\n"

