# version: '2'

# services:
#   proxy:
#     image: traefik
#     command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
#     networks:
#       - webgateway
#     ports:
#       - "70:70"
#       - "7070:7070"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /dev/null:/traefik.toml

# networks:
#   webgateway:
#     driver: bridge
#     
#     
traefik:
  image: traefik
  command: --web --docker --docker.domain=traefik.local --logLevel=DEBUG
  ports:
    - "71:80"
    - "7100:8080"
    # - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

vstb:
  image: katacoda/docker-http-server
  labels:
    - "traefik.backend=vstb"
    - "traefik.frontend.rule=Host:vstb.local"
stb:
  image: katacoda/docker-http-server:v2
  labels:
    - "traefik.backend=stb"
    - "traefik.frontend.rule=Host:stb.local"
