# version: '2'

# services:
#   proxy:
#     image: traefik
#     command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
#     networks:
#       - webgateway
#     ports:
#       - "70:70"
#       - "7070:7070"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - /dev/null:/traefik.toml

# networks:
#   webgateway:
#     driver: bridge
#     
#     
traefik:
  image: traefik
  command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  ports:
    - "71:71"
    - "7100:7100"
    # - "443:443"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml

machine:
  image: katacoda/docker-http-server
  labels:
    - "traefik.backend=machine-echo"
    - "traefik.frontend.rule=Host:machine-echo.example.com"

echo:
  image: katacoda/docker-http-server:v2
  labels:
    - "traefik.backend=echo"
    - "traefik.frontend.rule=Host:echo-echo.example.com"